-- MySQL Script generated by MySQL Workbench
-- Tue May  9 15:04:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema car-rent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car-rent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car-rent` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `car-rent` ;

-- -----------------------------------------------------
-- Table `car-rent`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-rent`.`car` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NULL DEFAULT NULL,
  `engine_capacity` VARCHAR(255) NULL DEFAULT NULL,
  `is_maintained` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARBINARY(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `plate_number` VARCHAR(255) NULL DEFAULT NULL,
  `seats_quantity` VARCHAR(255) NULL DEFAULT NULL,
  `stereo` VARCHAR(255) NULL DEFAULT NULL,
  `tariff` VARCHAR(255) NULL DEFAULT NULL,
  `year` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car-rent`.`rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-rent`.`rental` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `last_order_time` VARCHAR(255) NULL DEFAULT NULL,
  `order_quantity` VARCHAR(255) NULL DEFAULT NULL,
  `order_sum` VARCHAR(255) NULL DEFAULT NULL,
  `rental_date` VARCHAR(255) NULL DEFAULT NULL,
  `rental_time` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car-rent`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-rent`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date_of_birth` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car-rent`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-rent`.`orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `drive_length` VARCHAR(255) NULL DEFAULT NULL,
  `drive_price` VARCHAR(255) NULL DEFAULT NULL,
  `order_date` VARCHAR(255) NULL DEFAULT NULL,
  `order_time` VARCHAR(255) NULL DEFAULT NULL,
  `promocode` VARCHAR(255) NULL DEFAULT NULL,
  `car_id` BIGINT NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8ptpdp8fxan4etjis2wkqg1ea` (`car_id` ASC) VISIBLE,
  INDEX `FKbt2nbmdu9pi6afpuptj347c5` (`order_id` ASC) VISIBLE,
  INDEX `FKel9kyl84ego2otj2accfd8mr7` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK8ptpdp8fxan4etjis2wkqg1ea`
    FOREIGN KEY (`car_id`)
    REFERENCES `car-rent`.`car` (`id`),
  CONSTRAINT `FKbt2nbmdu9pi6afpuptj347c5`
    FOREIGN KEY (`order_id`)
    REFERENCES `car-rent`.`rental` (`id`),
  CONSTRAINT `FKel9kyl84ego2otj2accfd8mr7`
    FOREIGN KEY (`user_id`)
    REFERENCES `car-rent`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car-rent`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-rent`.`report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NULL DEFAULT NULL,
  `report_date` VARCHAR(255) NULL DEFAULT NULL,
  `report_time` VARCHAR(255) NULL DEFAULT NULL,
  `car_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKtbqh5kp1iq7t4tnbd176tlxjq` (`car_id` ASC) VISIBLE,
  CONSTRAINT `FKtbqh5kp1iq7t4tnbd176tlxjq`
    FOREIGN KEY (`car_id`)
    REFERENCES `car-rent`.`car` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
